name: Generate Documentation

on:
  push:
    branches:
      - '*'

jobs:
  generate-docs:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install curl
        run: |
          set CURL_DIR=%GITHUB_WORKSPACE%\curl-install
          if not exist "%CURL_DIR%" mkdir "%CURL_DIR%"
          cd "%CURL_DIR%"

          powershell -Command "Invoke-WebRequest -Uri 'https://curl.se/windows/dl-8.4.0_7/curl-8.4.0_7-win64-mingw.zip' -OutFile 'curl.zip'"
          powershell -Command "Expand-Archive -Path 'curl.zip' -DestinationPath ."

          for /d %%D in (curl-*-win64-mingw) do set CURL_FOLDER=%%D
          if exist "%CURL_FOLDER%\bin\curl.exe" (
            copy "%CURL_FOLDER%\bin\curl.exe" "%GITHUB_WORKSPACE%"
          ) else (
            echo "Error: curl.exe not found in extracted folder" >&2
            exit /b 1
          )

          cd "%GITHUB_WORKSPACE%"
          rmdir /s /q "%CURL_DIR%"
          echo "%GITHUB_WORKSPACE%" >> "%GITHUB_PATH%"
        shell: cmd

      - name: List all files in root
        run: dir /s /b
        shell: cmd

      - name: Manual Curl Test
        run: curl -k -G "https://devdocs-vftt.onrender.com/parseJavaCodeToJSON" ^
          --data-urlencode "owner=Ryuzaki5100" ^
          --data-urlencode "repo=devdocs" ^
          --data-urlencode "branch=master" ^
          --data-urlencode "filePath=demo/src/main/java/com/devdocs/demo/DemoApplication.java" ^
          --verbose
        shell: cmd

      - name: Generate java_files.txt
        run: batch_files\generateFileStructure.bat
        shell: cmd

      - name: Print java_files.txt
        run: type batch_files\java_files.txt
        shell: cmd

      - name: Process java_files.txt and Generate JSON
        run: batch_files\generateChunks.bat
        shell: cmd
        env:
          GH_OWNER: ${{ github.repository_owner }}
          GH_REPO: devdocs
          GH_BRANCH: ${{ github.ref_name }}

      - name: Print chunks.json
        run: type batch_files\chunks.json
        shell: cmd

      - name: Fetch Output JSON from API
        run: |
          curl -k -X POST "https://devdocs-vftt.onrender.com/postChunks" ^
            -H "Content-Type: application/json" ^
            --data "@batch_files\chunks.json" ^
            --output "batch_files\output.json" ^
            --verbose
        shell: cmd

      - name: Print output.json
        run: type batch_files\output.json
        shell: cmd

      - name: Generate Markdown Files from output.json
        run: batch_files\generateMarkdown.bat
        shell: cmd

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: cmd

      - name: List files in docs directory
        run: dir docs
        shell: cmd

      - name: Commit and Push Generated Files
        run: |
          git add batch_files\java_files.txt
          git add batch_files\chunks.json
          git add batch_files\output.json
          git add docs\*.md
          git add docs\images\*.png
          git diff --staged --quiet || git commit -m "Auto-generate documentation files [skip ci]"
          git push
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
